(function anylang_fr_he() {
  Anylang.addLang(
    {
      "langOrigin" : "fr",
      "langDestination": "he",
      "table" : [
         { from: '¨¨¨', to: 'ֻ' },
         { from: 'ou', to: 'וּ' },
         { from: 'aa', to: 'ָ' },
         { from: 'ee', to: 'ֶ' },
         { from: /Ch|ch(?=[ .])/, to: 'ך' },
         { from: 'ch', to: 'כ' },
         { from: 'rh', to: 'ח' },
         { from: /Ts|ts(?=[ .])/, to: 'ץ' },
         { from: 'ts', to: 'צ' },
         { from: 'sh', to: 'שׁ' },
         { from: 'ç', to: 'שׂ' },
         { from: 'a', to: 'ַ' },
         { from: 'e', to: 'ֵ' },
         { from: 'ô', to: 'ֹ' },
         { from: 'è', to: 'ֶ' },
         { from: 'é', to: 'ְ' },
         { from: 'i', to: 'ִ' },
         { from: '-', to: '־'},
         { from: 'o', to: 'וֹ' },
         { from: 'u', to: 'וּ' },
         { from: 'p', to: 'פּ' },
         { from: 'P', to: 'ף' },
         { from: 'b', to: 'בּ' },
         { from: '<', to: 'ּ' },
         { from: 'â', to: 'א' },
         { from: "'", to: 'א' },
         { from: 'v', to: 'ב' },
         { from: 'g', to: 'ג' },
         { from: 'd', to: 'ד' },
         { from: 'h', to: 'ה' },
         { from: 'w', to: 'ו' },
         { from: 'z', to: 'ז' },
         { from: 'k', to: 'ח' },
         { from: 'y', to: 'י' },
         { from: 'j', to: 'י' },
         { from: 'c', to: 'כּ' },
         { from: 'l', to: 'ל' },
         { from: /M|m(?=[ .])/, to: 'ם' },
         { from: 'm', to: 'מ' },
         { from: /N|n(?=[ .])/, to: 'ן' },
         { from: 'n', to: 'נ' },
         { from: 's', to: 'ס' },
         { from: '_', to: 'ע' },
         { from: 'f', to: 'פ' },
         { from: /F|f(?=[ .])/, to: 'ף' },
         { from: 'q', to: 'ק' },
         { from: 'r', to: 'ר' },
         { from: 'T', to: 'ט' },
         { from: 't', to: 'ת' },
         { from: '|', to: '' }
        ]
    });
})();

