(function anylang_fr_ru() {
  Anylang.addLang(
    {
      "langOrigin" : "fr",
      "langDestination": "ru",
      "table" : [
        {"from":"Chtch","to":"Щ"},
        {"from":"Tch","to":"Ч"},
        {"from":"Ch","to":"Ш"},
        {"from":"Ts","to":"Ц"},
        {"from":"Iu","to":"Ю"},
        {"from":"Ia","to":"Я"},
        {"from":"Io","to":"Ё"},
        {"from":"X","to":"Х"},
        {"from":"A","to":"А"},
        {"from":"B","to":"Б"},
        {"from":"V","to":"В"},
        {"from":"G","to":"Г"},
        {"from":"D","to":"Д"},
        {"from":"E","to":"Е"},
        {"from":"J","to":"Ж"},
        {"from":"Z","to":"З"},
        {"from":"I","to":"И"},
        {"from":"Î","to":"Й"},
        {"from":"K","to":"К"},
        {"from":"L","to":"Л"},
        {"from":"M","to":"М"},
        {"from":"N","to":"Н"},
        {"from":"O","to":"О"},
        {"from":"P","to":"П"},
        {"from":"R","to":"Р"},
        {"from":"S","to":"С"},
        {"from":"C","to":"С"},
        {"from":"T","to":"Т"},
        {"from":"U","to":"У"},
        {"from":"F","to":"Ф"},
        {"from":"Y","to":"Ы"},
        {"from":"È","to":"Э"},
        {"from":"chtch","to":"щ"},
        {"from":"tch","to":"ч"},
        {"from":"ch","to":"ш"},
        {"from":"ts","to":"ц"},
        {"from":"iu","to":"ю"},
        {"from":"ia","to":"я"},
        {"from":"io","to":"ё"},
        {"from":"x","to":"х"},
        {"from":"a","to":"а"},
        {"from":"b","to":"б"},
        {"from":"v","to":"в"},
        {"from":"g","to":"г"},
        {"from":"d","to":"д"},
        {"from":"e","to":"е"},
        {"from":"j","to":"ж"},
        {"from":"z","to":"з"},
        {"from":"i","to":"и"},
        {"from":"î","to":"й"},
        {"from":"k","to":"к"},
        {"from":"l","to":"л"},
        {"from":"m","to":"м"},
        {"from":"n","to":"н"},
        {"from":"o","to":"о"},
        {"from":"p","to":"п"},
        {"from":"r","to":"р"},
        {"from":"s","to":"с"},
        {"from":"c","to":"с"},
        {"from":"t","to":"т"},
        {"from":"u","to":"у"},
        {"from":"f","to":"ф"},
        {"from":'"',"to":"ъ"},
        {"from":"y","to":"ы"},
        {"from":"'","to":"ь"},
        {"from":"è","to":"э"},
        {"from":"*","to":"\u0301"}, // Accent
        {"from":'|',"to":''} //Separator to prevent to consecutive letters from being merged
        ]
    });
})();

