(function anylang_fr_he() {
  Anylang.addLang(
    {
      "langOrigin" : "fr",
      "langDestination": "he",
      "table" : [
        { from: /¨¨¨/g, to: 'ֻ' },
        { from: /ou/g, to: 'וּ' },
        { from: /aa/g, to: 'ָ' },
        { from: /ee/g, to: 'ֶ' },
        { from: /Ch|ch(?=[ .])/g, to: 'ך' },
        { from: /ch/g, to: 'כ' },
        { from: /rh/g, to: 'ח' },
        { from: /Ts|ts(?=[ .])/g, to: 'ץ' },
        { from: /ts/g, to: 'צ' },
        { from: /sh/g, to: 'שׁ' },
        { from: /ç/g, to: 'שׂ' },
        { from: /a/g, to: 'ַ' },
        { from: /e/g, to: 'ֵ' },
        { from: /ô/g, to: 'ֹ' },
        { from: /è/g, to: 'ֶ' },
        { from: /é/g, to: 'ְ' },
        { from: /i/g, to: 'ִ' },
        { from: /-/g, to: '־'},
        { from: /o/g, to: 'וֹ' },
        { from: /u/g, to: 'וּ' },
        { from: /p/g, to: 'פּ' },
        { from: /P/g, to: 'ף' },
        { from: /b/g, to: 'בּ' },
        { from: /</g, to: 'ּ' },
        { from: /â/g, to: 'א' },
        { from: /'/g, to: 'א' },
        { from: /v/g, to: 'ב' },
        { from: /g/g, to: 'ג' },
        { from: /d/g, to: 'ד' },
        { from: /h/g, to: 'ה' },
        { from: /w/g, to: 'ו' },
        { from: /z/g, to: 'ז' },
        { from: /k/g, to: 'ח' },
        { from: /y/g, to: 'י' },
        { from: /j/g, to: 'י' },
        { from: /c/g, to: 'כּ' },
        { from: /l/g, to: 'ל' },
        { from: /M|m(?=[ .])/g, to: 'ם' },
        { from: /m/g, to: 'מ' },
        { from: /N|n(?=[ .])/g, to: 'ן' },
        { from: /n/g, to: 'נ' },
        { from: /s/g, to: 'ס' },
        { from: /_/g, to: 'ע' },
        { from: /f/g, to: 'פ' },
        { from: /F|f(?=[ .])/g, to: 'ף' },
        { from: /q/g, to: 'ק' },
        { from: /r/g, to: 'ר' },
        { from: /T/g, to: 'ט' },
        { from: /t/g, to: 'ת' },
        { from: /\|/g, to: '' } //Separator to prevent to consecutive letters from being merged
        ]
    });
})();

